version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  - source: /
    destination: /home/ubuntu/instrument_generator
  - source: deploy/nginx/instrument_generator.conf
    destination: /etc/nginx/sites-enabled/instrument_generator
hooks:
  BeforeInstall:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_deps.sh
      timeout: 900
      runas: ubuntu
    - location: scripts/reload-nginx.sh
      timeout: 300
      runas: root
    - location: scripts/migrate_and_collectstatic.sh
      timeout: 900
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 300
      runas: ubuntu
