version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "----- Create virtualenv and install deps -----"
      - python -m venv .venv
      - .venv/bin/pip install --upgrade pip
      - .venv/bin/pip install -r requirements.txt

  pre_build:
    commands:
      - echo "----- Running tests -----"
      # Hier gebruik je de venv‑pytest, niet 'pytest' alleen:
      - .venv/bin/pytest --maxfail=1 --disable-warnings -q

  build:
    commands:
      - echo "----- Build complete, packaging artifact -----"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - "**/*"
  discard-paths: no
