# Generated by Django 5.2 on 2025-05-09 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('considerations', models.TextField(blank=True)),
                ('requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitters_data', models.JSONField(default=list)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='instruments.instrumentsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
