# Generated by Django 5.2 on 2025-04-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentsubmission',
            name='favorited_by',
        ),
    ]
