# Generated by Django 5.2 on 2025-05-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='comment',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='request_comment',
            field=models.TextField(blank=True, help_text='Toelichting van de aanvrager bij het verzoek'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='review_comment',
            field=models.TextField(blank=True, help_text='Commentaar van de beoordelaar bij goed- of afkeuring'),
        ),
    ]
