# Generated by Django 5.2 on 2025-05-09 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_migrate_comments'),
        ('instruments', '0002_instrumentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='instruments.instrumentversion'),
        ),
    ]
