# Generated by Django 5.2 on 2025-05-09 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_approvalrequest_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('members', models.ManyToManyField(related_name='approval_groups', to=settings.AUTH_USER_MODEL, verbose_name='Leden')),
            ],
            options={
                'verbose_name': 'Goedkeuringsgroep',
                'verbose_name_plural': 'Goedkeuringsgroepen',
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='required_groups',
            field=models.ManyToManyField(help_text='Groepen die dit verzoek moeten goedkeuren', related_name='assigned_requests', to='approvals.approvalgroup', verbose_name='Vereiste goedkeuringsgroepen'),
        ),
        migrations.CreateModel(
            name='GroupApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'In afwachting'), ('APPROVED', 'Goedgekeurd'), ('REJECTED', 'Afgekeurd')], default='PENDING', max_length=10, verbose_name='Status')),
                ('review_comment', models.TextField(blank=True, help_text='Commentaar van de beoordelaar bij goed- of afkeuring', verbose_name='Commentaar')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Beoordeeld op')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_approvals', to='approvals.approvalrequest', verbose_name='Goedkeuringsverzoek')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='approvals.approvalgroup', verbose_name='Groep')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Beoordelaar')),
            ],
            options={
                'verbose_name': 'Groepsgoedkeuring',
                'verbose_name_plural': 'Groepsgoedkeuringen',
                'unique_together': {('approval_request', 'group')},
            },
        ),
    ]
