# Generated by Django 5.2 on 2025-05-10 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_approvalgroup_approvalrequest_required_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapproval',
            name='approved_members',
            field=models.ManyToManyField(blank=True, related_name='approved_group_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Leden die hebben goedgekeurd'),
        ),
        migrations.AddField(
            model_name='groupapproval',
            name='rejected_members',
            field=models.ManyToManyField(blank=True, related_name='rejected_group_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Leden die hebben afgewezen'),
        ),
    ]
